image: ruby2.0.0
env:
  USE_SYSTEM_GECODE=1
script:
  - sudo apt-get update
  - sudo apt-get install libgecode-dev
  - bundle install --path vendor --binstubs
  - bin/berks install
  - bin/rake style spec